<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="error-template">
                <h1><?php echo $this->translate('Oops!') ?></h1>
                <h2><?php echo $this->translate('403 Not Allow'); ?></h2>
                <div class="error-details">
                    <?php echo $this->translate('Sorry, an error has occured, Requested page not found!'); ?>
                </div>
                <div class="error-actions">
                    <a href="<?php echo $this->url('home'); ?>" class="btn btn-primary btn-lg">
                        <span class="glyphicon glyphicon-home"></span> <?php echo $this->translate('Take Me Home'); ?>
                    </a>
                    <a href="#" class="btn btn-default btn-lg">
                        <span class="glyphicon glyphicon-envelope"></span> <?php echo $this->translate('Contact Support'); ?>
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>
